version: "3.9"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my-network

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.6
    container_name: aspire-dashboard
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - 18888:18888
      - 4317:18889
    networks:
      - my-network
      
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Th3_P@ssw0rd-421
    ports:
      - "1433:1433"
    networks:
      - my-network
    volumes:
      - mssql_data:/var/opt/mssql
      
  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass Th3_P@ssw0rd-421"
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my-network
      
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" 
      - "8025:8025" 
      
  # my-app:
    # image: my-app
    # container_name: my-app
    # build:
      # context: .
      # dockerfile: src/CA.And.DDD.Template.WebApi/Dockerfile
    # environment:
       # - AppSettings__Redis__Host=redis
       # - AppSettings__RabbitMq__Host=amqp://rabbitmq
       # - AppSettings__Telemetry__Host=http://aspire-dashboard
       # - AppSettings__Telemetry__Port=18889
       # - AppSettings__MsSql__ConnectionString=Server=mssql;Database=CleanArchitectureAndDDD;User Id=sa;Password=Th3_P@ssw0rd-421;TrustServerCertificate=True
    # ports:
      # - 8080:8080
      # - 8081:8081
    # networks:
      # - my-network
      
  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://posgresdb:5432/keycloak
      KC_DB_USERNAME: sa_user
      KC_DB_PASSWORD: Th3_P@ssw0rd-421

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - posgresdb
    ports:
      - 8080:8080

  posgresdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak #TODO: move it
      POSTGRES_USER: sa_user
      POSTGRES_PASSWORD: Th3_P@ssw0rd-421 
      
volumes:
  rabbitmq_data:
  redis_data:
  mssql_data:
  postgres_data:
  
networks:
  my-network: